# Generated by Django 4.2.5 on 2023-11-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_helpme_item_remove_icanhelp_items_helpme_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpme',
            name='item',
        ),
        migrations.RemoveField(
            model_name='icanhelp',
            name='items',
        ),
        migrations.AddField(
            model_name='helpme',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.science'),
        ),
        migrations.AddField(
            model_name='icanhelp',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.science'),
        ),
    ]
